workflows:
  # ionic-capacitor-ios-workflow:
  #   environment:
  #     groups:
  #       - group-name
  # ionic-capacitor-android-workflow:
  #   environment:
  #     groups:
  #       - group-name
  hello-world:
    name: Hello world workflow
    max_build_duration: 100
    environment:
      groups:
        - capgo_credentials
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install @capgo/capacitor-updater
          npx @capgo/cli login $CAPGO_TOKEN
      - name: Build
        script: |
          npm run build:sync
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap sync
      - name: Upload to Capgo
        script: |
          npx @capgo/cli bundle upload -c production
