workflows:
  # ionic-capacitor-ios-workflow:
  #   environment:
  #     groups:
  #       - group-name
  # ionic-capacitor-android-workflow:
  #   environment:
  #     groups:
  #       - group-name
  hello-world:
    name: Hello world workflow
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install NPM Packages
        script: npm ci